[unix_http_server]
file=/home/container/tmp/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/home/container/tmp/supervisord.pid
childlogdir=/home/container/tmp

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///home/container/tmp/supervisor.sock

[include]
files = /etc/supervisor/conf.d/*.conf
